import type { Habit, Session, Task } from '../types'

const nowIso = '2026-04-13T09:00:00.000Z'

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Plan weekly priorities',
    description: 'Align top goals and lock time blocks for deep work.',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-04-14T17:00:00.000Z',
    estimateMinutes: 45,
    tags: ['planning', 'focus'],
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'task-2',
    title: 'Review habit trends',
    status: 'planned',
    priority: 'medium',
    dueDate: '2026-04-15T20:00:00.000Z',
    estimateMinutes: 30,
    tags: ['analytics'],
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'task-3',
    title: 'Prototype timeline widget',
    description: 'Sketch first interactive timeline lane for daily sessions.',
    status: 'backlog',
    priority: 'critical',
    estimateMinutes: 120,
    tags: ['ui', 'timeline'],
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'task-4',
    title: 'Sync health data import',
    status: 'blocked',
    priority: 'high',
    tags: ['health', 'integrations'],
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'task-5',
    title: 'Refactor shared card component',
    status: 'done',
    priority: 'low',
    estimateMinutes: 50,
    tags: ['frontend'],
    createdAt: nowIso,
    updatedAt: '2026-04-13T11:15:00.000Z',
  },
]

export const mockHabits: Habit[] = [
  {
    id: 'habit-1',
    name: 'Morning deep work',
    description: '90-minute distraction-free session before noon.',
    cadence: 'daily',
    targetCount: 1,
    streak: 6,
    bestStreak: 14,
    lastCompletedAt: '2026-04-13T08:35:00.000Z',
    active: true,
    tags: ['focus', 'productivity'],
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'habit-2',
    name: 'Strength training',
    cadence: 'weekly',
    targetCount: 4,
    streak: 3,
    bestStreak: 8,
    lastCompletedAt: '2026-04-12T18:10:00.000Z',
    active: true,
    tags: ['fitness', 'health'],
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'habit-3',
    name: 'Monthly retrospective',
    cadence: 'monthly',
    targetCount: 1,
    streak: 2,
    bestStreak: 5,
    lastCompletedAt: '2026-03-31T21:00:00.000Z',
    active: true,
    tags: ['reflection'],
    createdAt: nowIso,
    updatedAt: nowIso,
  },
]

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    label: 'Deep Work Block',
    type: 'focus',
    startTime: '2026-04-13T08:00:00.000Z',
    endTime: '2026-04-13T09:30:00.000Z',
    timezone: 'UTC',
    energyLevel: 8,
    notes: 'No meetings, sprint architecture review.',
    source: 'manual',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'session-2',
    label: 'Walk + recovery',
    type: 'break',
    startTime: '2026-04-13T09:30:00.000Z',
    endTime: '2026-04-13T10:00:00.000Z',
    timezone: 'UTC',
    energyLevel: 7,
    source: 'generated',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
  {
    id: 'session-3',
    label: 'Planning admin',
    type: 'admin',
    startTime: '2026-04-13T10:15:00.000Z',
    endTime: '2026-04-13T11:00:00.000Z',
    timezone: 'UTC',
    energyLevel: 6,
    notes: 'Inbox cleanup and weekly roadmap updates.',
    source: 'imported',
    createdAt: nowIso,
    updatedAt: nowIso,
  },
]

export const mockDataset = {
  tasks: mockTasks,
  habits: mockHabits,
  sessions: mockSessions,
}
